"""Rebuild the offline asset catalogue from the JSON card definitions. Python 3 only."""
from pathlib import Path
from html import escape
import json
ROOT=Path(__file__).resolve().parents[1]
def e(s):return escape(str(s),quote=True)
sections=[]
for game,title,description in [('clockwork-rivals','Clockwork Rivals','Build a spatial machine engine; compete for fuel and public commissions.'),('living-frontier','Living Frontier','Develop organisms; reshape the shared map and contest habitats.')]:
 data=json.loads((ROOT/'data'/f'{game}.json').read_text())
 cards=data.get('parts',data.get('cards'))
 items=[]
 for c in cards:
  is_full=c['art'].endswith('.png')
  cost=f"{c['growthCost']} growth" if 'growthCost' in c else 'Free draft / install'
  items.append(f'''<article class="game-card"><div class="card-top"><span>{e(c['category'])}</span><span>{e(cost)}</span></div><div class="art {'fallback' if not is_full else ''}"><img src="{e(c['art'])}" alt="{e(c['name'])} illustration" loading="lazy"></div><div class="card-copy"><h3>{e(c['name'])}</h3><p>{e(c['rulesText'])}</p></div><div class="card-id">{e(c['id'])} · {'Source art' if is_full else 'SVG placeholder'}</div></article>''')
 if 'commissions' in data:
  order_html='<div class="orders">'+''.join(f'<div><img src="{o["art"]}" alt=""><strong>{e(o["name"])}</strong><span>{o["gearCost"]} gears → {o["prestige"]} prestige</span></div>' for o in data['commissions'])+'</div>'
 else:order_html='<div class="tiles">'+''.join(f'<figure><img src="assets/living-frontier/tile-{x}.svg" alt="{x} tile"><figcaption>{x.title()}</figcaption></figure>' for x in ['meadow','wetland','woodland'])+'</div>'
 sections.append(f'''<section id="{game}" class="game-section {game}"><div class="section-heading"><div><div class="eyebrow">PROTOTYPE 0.1 · TWO PLAYERS</div><h2>{title}</h2><p>{description}</p></div><a href="docs/{game}/PLAN.md">Read game plan ↗</a></div><div class="cards">{''.join(items)}</div>{order_html}</section>''')
html='''<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Boardgames — development kit</title>
<link rel="stylesheet" href="assets/ui/tokens.css">
<style>
*{box-sizing:border-box}body{margin:0;background:#f5f1e8;color:#182d33;font-family:system-ui,-apple-system,Segoe UI,sans-serif;font-size:16px;line-height:1.55}main{max-width:1280px;margin:auto;padding:44px 28px 70px}.eyebrow{font-size:12px;letter-spacing:.15em;font-weight:700;color:#696859}h1,h2,h3{font-family:Georgia,serif;line-height:1.15}h1{font-size:clamp(34px,5vw,60px);font-weight:400;margin:12px 0}header>p{max-width:720px;color:#53605c}nav{display:flex;gap:12px;flex-wrap:wrap;margin:26px 0 44px}a{color:inherit;text-decoration-thickness:1px;text-underline-offset:4px}nav a{padding:12px 18px;border:1px solid #b4b6a9;border-radius:5px;text-decoration:none;background:#fffaf2}.section-heading{display:flex;justify-content:space-between;align-items:center;gap:20px;margin:0 0 24px}.section-heading p{max-width:700px}.section-heading>a{white-space:nowrap}h2{font-size:36px;margin:8px 0}.game-section{margin:50px 0 65px;padding-top:25px;border-top:1px solid #bbb9ac}.cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:22px}.game-card{border:1px solid #a68b65;border-radius:10px;background:#fffaf0;overflow:hidden;display:flex;flex-direction:column}.card-top{display:flex;justify-content:space-between;gap:10px;padding:10px 14px;background:#203640;color:#fff9e8;font-size:12px;text-transform:uppercase;letter-spacing:.03em}.art{aspect-ratio:1/1;background:#f9f2df}.art img{height:100%;width:100%;object-fit:contain;display:block}.art.fallback{display:grid;place-items:center;background:#f0ebdf}.art.fallback img{width:45%;height:45%}.card-copy{padding:18px 20px;flex:1}.card-copy h3{font-size:26px;margin:0 0 12px}.card-copy p{margin:0}.card-id{padding:9px 20px;border-top:1px solid #d5cab6;color:#696557;font-size:12px}.living-frontier{color:#193d32}.living-frontier .game-card{border-color:#8d9f88}.living-frontier .card-top{background:#204b3e}.orders{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:22px}.orders>div{padding:18px;border:1px solid #c6b18e;display:grid;grid-template-columns:45px 1fr;column-gap:15px;align-items:center}.orders img{width:45px;grid-row:span 2}.orders span{font-size:14px}.tiles{display:flex;gap:25px;justify-content:center;margin-top:24px}.tiles figure{margin:0;text-align:center;max-width:220px}.tiles img{width:100%}footer{color:#5b665e;border-top:1px solid #bbb9ac;padding-top:25px}footer a{margin-right:20px}@media(max-width:900px){.cards{grid-template-columns:repeat(2,minmax(0,1fr))}.section-heading{display:block}.orders{grid-template-columns:1fr}}@media(max-width:550px){main{padding:24px 16px}.cards{grid-template-columns:1fr}h2{font-size:30px}.tiles{gap:6px}.card-copy{padding:18px}nav{margin-bottom:20px}.game-section{margin-top:30px}}
</style></head><body><main><header><div class="eyebrow">IVAN TRETYAKOV · DEVELOPMENT HANDOFF</div><h1>Two worlds. One first prototype.</h1><p>Browse the starter art and editable card definitions. This catalogue is not a playable game. Exact effects are proposed for testing; the written plans define the complete loop.</p><nav><a href="#clockwork-rivals">Clockwork Rivals</a><a href="#living-frontier">Living Frontier</a><a href="AGENT-START.md">Coding-agent handoff ↗</a></nav></header>'''+''.join(sections)+'''<footer><p>Six source illustrations, reusable SVG components and versioned card data. Card text stays editable.</p><a href="README.md">Start here</a><a href="docs/ENGINE-RECOMMENDATION.md">Engine research</a><a href="assets/manifest.json">Asset manifest</a></footer></main></body></html>'''
(ROOT/'preview.html').write_text(html)
print('Wrote preview.html')
